//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Education
    {
        public int Id { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public string Institute_University { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> GraduationMonth { get; set; }
        public string Qualification { get; set; }
        public string Institute_UniversityLocation { get; set; }
        public string FieldOfStudy { get; set; }
        public string Grade { get; set; }
        public string AdditionalInformation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Trainer Trainer { get; set; }
        public virtual Year Year { get; set; }
    }
}
