//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimetablePerDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimetablePerDay()
        {
            this.AttendancePerDay = new HashSet<AttendancePerDay>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TimetableId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> MorningTrainerId { get; set; }
        public string MorningRemark { get; set; }
        public Nullable<int> AfternoonTrainerId { get; set; }
        public string AfternoonRemark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendancePerDay> AttendancePerDay { get; set; }
        public virtual Timetable Timetable { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual Trainer Trainer1 { get; set; }
    }
}
